In [55]:
import pandas as pd

# Load the Excel file to see the content
file_path = r"D:\stage\data\Detail_Courbes et Dispositifs_CH Saint Denis_20211001.xlsx"
excel_data = pd.ExcelFile(file_path)

# Get the names of all the sheets in the Excel file
sheet_names = excel_data.sheet_names
sheet_names

['Dispositifs Courbes',
 'Moniteurs Philips',
 'Moniteur PICCO 2',
 'Respirateurs V500&V800']

In [56]:
# Récupérer les 3 feuilles  de calculs :  'Moniteurs Philips', 'Moniteur PICCO 2','Respirateurs V500&V800'
# On récupère chaque feuille dans un dataframe distinct

data_philips = pd.read_excel(r"D:\stage\data\Detail_Courbes et Dispositifs_CH Saint Denis_20211001.xlsx", sheet_name='Moniteurs Philips')

data_pulsion = pd.read_excel(r"D:\stage\data\Detail_Courbes et Dispositifs_CH Saint Denis_20211001.xlsx", sheet_name='Moniteur PICCO 2')

data_drager = pd.read_excel(r"D:\stage\data\Detail_Courbes et Dispositifs_CH Saint Denis_20211001.xlsx", sheet_name='Respirateurs V500&V800')

In [57]:
# Données Moniteur philips
data_philips.head()

,ID,Label,Group,Device,Source
0,9165,Edi Diaphragm Electrical Activity Waveform,Waveforms,"IntelliVue MP70, Intellivue MP20, Intellivue X...",Waves: EDI
1,6331,Fetal DECG Wave,Waveforms,"IntelliVue MP70, Intellivue MP20, Intellivue X...",Waves: DECG
2,7000,ECG Lead V3R Wave,Waveforms,"IntelliVue MP70, Intellivue MP20, Intellivue X...",Waves: V3R
3,6323,ECG Lead V8 Wave,Waveforms,"IntelliVue MP70, Intellivue MP20, Intellivue X...",Waves: V8
4,6326,Airway Aux Wave,Waveforms,"IntelliVue MP70, Intellivue MP20, Intellivue X...",Waves: AWPx

In [58]:
data_philips.columns

Index(['ID', 'Label', 'Group  ', 'Device', 'Source'], dtype='object')

In [59]:
# Extraire les colonnes nécessaires
colonnes = ['ID', 'Label']
data = data_philips[colonnes].assign(Unit=pd.NA, Device='Philips').sort_values(by='Label') # ajouter des colonnes unit et Device, puis trier les valeurs au même temps

display(data)

      ID                                   Label Unit   Device
15  8656         Accoustic Respiration Rate Wave  NaN  Philips
4   6326                         Airway Aux Wave  NaN  Philips
87  8866               Airway CO2 Level Waveform  NaN  Philips
43  8788                        Airway Flow Wave  NaN  Philips
67  8868                          Airway N2 Wave  NaN  Philips
..   ...                                     ...  ...      ...
51  8861        Right Atrial Pressure (RAP) Wave  NaN  Philips
39   624          Sevoflurane Concentration Wave  NaN  Philips
64  8864  Umbilical Arterial Pressure (UAP) Wave  NaN  Philips
44  8865    Umbilical Venous Pressure (UVP) Wave  NaN  Philips
65  8875                         Vector ECG Wave  NaN  Philips

[91 rows x 4 columns]

In [60]:
# Données pulsion (Picco 2)
data_pulsion.head()

     ID                         Label  Unit     Group                   Source
0  6694  Arterial Blood Pressure Wave  mmHg  Waveforms   Continuous Parameter

In [61]:
# Extraire les trois colonnes id, label et unit, puis concaténer le résultat avec data
data = pd.concat([data, data_pulsion[['ID', 'Label', 'Unit']].assign(Device='Pulsion')], ignore_index=True)
display(data)

      ID                                   Label  Unit   Device
0   8656         Accoustic Respiration Rate Wave   NaN  Philips
1   6326                         Airway Aux Wave   NaN  Philips
2   8866               Airway CO2 Level Waveform   NaN  Philips
3   8788                        Airway Flow Wave   NaN  Philips
4   8868                          Airway N2 Wave   NaN  Philips
..   ...                                     ...   ...      ...
87   624          Sevoflurane Concentration Wave   NaN  Philips
88  8864  Umbilical Arterial Pressure (UAP) Wave   NaN  Philips
89  8865    Umbilical Venous Pressure (UVP) Wave   NaN  Philips
90  8875                         Vector ECG Wave   NaN  Philips
91  6694            Arterial Blood Pressure Wave  mmHg  Pulsion

[92 rows x 4 columns]

In [62]:
# Données Drager ('Respirateurs V500&V800')
display(data_drager)

     ID                          Label   Unit     Group
0   114     CO2 Concentration Waveform      -  Waveforms
1   118               Airway Flow Wave  L/min  Waveforms
2  1575           Respired Volume Wave     mL  Waveforms
3  2542           Airway Pressure Wave   mbar  Waveforms
4  4732      Inspiratory Flow Waveform  L/min  Waveforms
5  7872  CO2 Partial Pressure Waveform      -  Waveforms
6  9163     Tracheal Pressure Waveform   mbar  Waveforms

In [63]:
data = pd.concat([data, data_drager[['ID', 'Label', 'Unit']].assign(Device='drager')])
display(data)

      ID                            Label   Unit   Device
0   8656  Accoustic Respiration Rate Wave    NaN  Philips
1   6326                  Airway Aux Wave    NaN  Philips
2   8866        Airway CO2 Level Waveform    NaN  Philips
3   8788                 Airway Flow Wave    NaN  Philips
4   8868                   Airway N2 Wave    NaN  Philips
..   ...                              ...    ...      ...
2   1575             Respired Volume Wave     mL   drager
3   2542             Airway Pressure Wave   mbar   drager
4   4732        Inspiratory Flow Waveform  L/min   drager
5   7872    CO2 Partial Pressure Waveform      -   drager
6   9163       Tracheal Pressure Waveform   mbar   drager

[99 rows x 4 columns]

In [64]:
# Ajouter une colonne format avec comme valeur Waveforms
data = data.assign(Format='WaveForms')
display(data)

      ID                            Label   Unit   Device     Format
0   8656  Accoustic Respiration Rate Wave    NaN  Philips  WaveForms
1   6326                  Airway Aux Wave    NaN  Philips  WaveForms
2   8866        Airway CO2 Level Waveform    NaN  Philips  WaveForms
3   8788                 Airway Flow Wave    NaN  Philips  WaveForms
4   8868                   Airway N2 Wave    NaN  Philips  WaveForms
..   ...                              ...    ...      ...        ...
2   1575             Respired Volume Wave     mL   drager  WaveForms
3   2542             Airway Pressure Wave   mbar   drager  WaveForms
4   4732        Inspiratory Flow Waveform  L/min   drager  WaveForms
5   7872    CO2 Partial Pressure Waveform      -   drager  WaveForms
6   9163       Tracheal Pressure Waveform   mbar   drager  WaveForms

[99 rows x 5 columns]

In [65]:
# sauvegarder sous format excel et csv
data.to_excel(r"C:\Users\AdminPC\sepsis_prediction\sepsis_prediction\exploration du sujet\variables_wave.xlsx", index=False)
data.to_csv(r"C:\Users\AdminPC\sepsis_prediction\sepsis_prediction\exploration du sujet\variables_wave.csv", index=False)